eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://wolf:abc123@localhost:8761/eureka/
security:
  basic:    
    enabled: true    
  user:    
    name: wolf
    password: abc123
server:
  port: 9000
